name: Flake8 your PR
on: [pull_request]
jobs:
  flake8-your-pr:
    runs-on: ubuntu-latest
    container: giapbnv/flake8-your-pullrequest:1.0
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: ./git_ci_config/
#      - uses: tayfun/flake8-your-pr@master
#      - uses: valentijnscholten/flake8-your-pr@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
